server:
  port: 0
  
spring:
  boot:
    admin:
      url: http://localhost:8089
  cloud:
    consul:
      discovery:
        instanceId: ${spring.application.name}:${random.value}
        health-check-interval: 5s
      config:
        management: 
          enabled: true
    stream:
      bindings:
        output:
          binder: kafka
          destination: cloudEX
management:
  endpoints:
    web:
     exposure:
       include: *
  security: 
    enabled: false
